### ISSUE TITLE
Status of component

### ISSUE THREAD

**Issue by mrbatista** [Oneflow/loopback-component-primus#1]
@pierissimo  What is the status of this component?

**Comment by pierissimo** [comment]
hi @mrbatista 
The strong-remoting package now accepts external adapters ( as per: https://github.com/strongloop/strong-remoting/pull/408).

The Primus Adapter code works, it needs to be packaged as a reusable component (that is the purpose of this repo).
It will be completed in the next few weeks.

**Comment by pierissimo** [comment]
hi @mrbatista.
The project has been updated with readme and examples.
